version: '3.8'
name: 'totallatorv3'

services:
  totallatorv3:
    image: ghcr.io/qwacko/totallatorv3:latest
    environment:
      - ORIGIN=https://www.example.com
      - PORT=3000
      - ALLOW_SIGNUP=false
      - BACKUP_DIR=./backup/
      - IMPORT_DIR=./import/
      - BACKUP_SCHEDULE="0 0 * * *"
      - DB_QUERY_LOG=false
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/totallatorv3
      - BODY_SIZE_LIMIT=10000000
      - DISABLE_BUFFERING=true
    volumes:
      - ./backup:/app/backup
      - ./import:/app/import
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=totallatorv3
      - PGDATA=/data/postgres
    volumes:
      - ./db:/data/postgres
    restart: unless-stopped
