version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1001
        USER_GID: 1001
    # env_file:
    #     - .env
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    # volumes:
    #   - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=totallatorv3
      - PGDATA=/data/postgres
    volumes:
      - db_data:/data/postgres
    restart: unless-stopped

volumes:
  db_data: