version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1001
        USER_GID: 1001
    # env_file:
    #     - .env
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    # volumes:
    #   - ..:/workspaces:cached
    command: sleep infinity
    # depends_on:
    #   - postgres
