CREATE INDEX IF NOT EXISTS "account_title_idx" ON "account" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_type_idx" ON "account" ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_is_cash_idx" ON "account" ("is_cash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_is_net_worth_idx" ON "account" ("is_net_worth");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_account_group_combined_idx" ON "account" ("account_group_combined");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_account_title_combined_idx" ON "account" ("account_title_combined");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bill_title_idx" ON "bill" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bill_summary_id_idx" ON "bill" ("summary_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "budget_title_idx" ON "budget" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "budget_summary_id_idx" ON "budget" ("summary_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_title_idx" ON "category" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_group_idx" ON "category" ("group");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_single_idx" ON "category" ("single");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_summary_id_idx" ON "category" ("summary_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_created_at_idx" ON "journal_entry" ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_transaction_id_idx" ON "journal_entry" ("transaction_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_date_amount_idx" ON "journal_entry" ("date","amount");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_date_idx" ON "journal_entry" ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_date_text_idx" ON "journal_entry" ("date_text");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_description_idx" ON "journal_entry" ("description");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_transfer_idx" ON "journal_entry" ("transfer");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_complete_idx" ON "journal_entry" ("complete");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_reconciled_idx" ON "journal_entry" ("reconciled");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_data_checked_idx" ON "journal_entry" ("data_checked");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_account_id_idx" ON "journal_entry" ("account_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_bill_id_idx" ON "journal_entry" ("bill_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_budget_id_idx" ON "journal_entry" ("budget_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_category_id_idx" ON "journal_entry" ("category_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_tag_id_idx" ON "journal_entry" ("tag_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_import_id_idx" ON "journal_entry" ("import_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_import_detail_id_idx" ON "journal_entry" ("import_detail_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "journalEntry_year_month_idx" ON "journal_entry" ("year_month");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_title_idx" ON "filter" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_group_idx" ON "filter" ("group");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_can_apply_idx" ON "filter" ("can_apply");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_needs_update_idx" ON "filter" ("needs_update");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_apply_automatically_idx" ON "filter" ("apply_automatically");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_apply_following_import_idx" ON "filter" ("apply_following_import");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_listed_idx" ON "filter" ("listed");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "filter_modification_type_idx" ON "filter" ("modification_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "summary_type_idx" ON "summary" ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "summary_relation_idx" ON "summary" ("relation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "summary_needs_update_idx" ON "summary" ("needs_update");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tag_title_idx" ON "tag" ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tag_group_idx" ON "tag" ("group");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tag_single_idx" ON "tag" ("single");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tag_summary_id_idx" ON "tag" ("summary_id");