import { serverEnvSchema } from '@totallator/shared';

import { dev } from '$app/environment';

import { env } from '$env/dynamic/private';

export const getServerEnv = () =>
	serverEnvSchema.parse({
		DEV: dev,
		LOGGING: env.LOGGING,
		LOGGING_CLASSES: env.LOGGING_CLASSES,
		PAGE_TIMEOUT_MS: env.PAGE_TIMEOUT_MS,
		BACKUP_DIR: env.BACKUP_DIR,
		FILE_DIR: env.FILE_DIR,
		BACKUP_SCHEDULE: env.BACKUP_SCHEDULE,
		AUTOMATIC_FILTER_SCHEDULE: env.AUTOMATIC_FILTER_SCHEDULE,
		IMPORT_DIR: env.IMPORT_DIR,
		ALLOW_SIGNUP: env.ALLOW_SIGNUP,
		DEV_OVERRIDE: env.DEV_OVERRIDE,
		DB_QUERY_LOG: env.DB_QUERY_LOG,
		TESTING_DELAY: env.TESTING_DELAY,
		DISABLE_BUFFERING: env.DISABLE_BUFFERING,
		TEST_ENV: env.TEST_ENV,
		POSTGRES_URL: env.POSTGRES_URL,
		POSTGRES_TEST_URL: env.POSTGRES_TEST_URL,
		POSTGRES_MAX_CONNECTIONS: env.POSTGRES_MAX_CONNECTIONS,
		IMPORT_TIMEOUT_MIN: env.IMPORT_TIMEOUT_MIN,
		RETENTION_MONTHS: env.RETENTION_MONTHS,
		IMPORT_RETENTION_DAYS: env.IMPORT_RETENTION_DAYS,
		S3_ACCESS_KEY_ID: env.S3_ACCESS_KEY_ID,
		S3_SECRET_ACCESS_KEY: env.S3_SECRET_ACCESS_KEY,
		S3_ACCESS_URL: env.S3_ACCESS_URL,
		S3_REGION: env.S3_REGION,
		S3_DISABLE_CHECKSUM: env.S3_DISABLE_CHECKSUM,
		DBLOG_ENABLE: env.DBLOG_ENABLE,
		DBLOG_CACHE_SIZE: env.DBLOG_CACHE_SIZE,
		DBLOG_CACHE_TIMEOUT: env.DBLOG_CACHE_TIMEOUT,
		TRANSACTIONLOG_ENABLE: env.TRANSACTIONLOG_ENABLE,
		TRANSACTIONLOG_TIME_MS: env.TRANSACTIONLOG_TIME_MS,
		TRANSACTIONLOG_ENABLESTART: env.TRANSACTIONLOG_ENABLESTART,
		CONCURRENT_REFRESH: env.CONCURRENT_REFRESH,
		VIEW_REFRESH_TIMEOUT: env.VIEW_REFRESH_TIMEOUT,
		LLM_REVIEW_ENABLED: env.LLM_REVIEW_ENABLED,
		LLM_REVIEW_AUTO_IMPORT: env.LLM_REVIEW_AUTO_IMPORT,
		LLM_REVIEW_MANUAL_CREATE: env.LLM_REVIEW_MANUAL_CREATE,
		LLM_REVIEW_SCHEDULE: env.LLM_REVIEW_SCHEDULE,
		LLM_AUTO_CREATE_ITEMS: env.LLM_AUTO_CREATE_ITEMS,
		ENCRYPTION_KEY: env.ENCRYPTION_KEY,
		DBLOG_STORAGE_HOURS: env.DBLOG_STORAGE_HOURS,
		DBLOG_STORAGE_COUNT: env.DBLOG_STORAGE_COUNT
	});

export const serverEnv = getServerEnv();
