name: Tests and Checks

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  test_and_check:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      POSTGRES_URL: postgres://postgres:postgres@localhost:5432/postgres
      POSTGRES_TEST_URL: postgres://postgres:postgres@localhost:5432/postgres

    steps:
      # Setup Postgres
      - uses: ikalnytskyi/action-setup-postgres@v4
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
      
      # Build all packages so their TypeScript declarations are available
      - run: pnpm build
      
      - run: pnpm check
      - run: pnpm test:unit
